# Monotrail Dual Cascading Envelopes v1


[p2b8]

# -------------------------------- envelopes group 1

[contour]
    trigger = I1 + _EOA_1_RETRIGGER
    loop = L1.3
    attack = _POT_1_1 * 20
    release = _POT_1_2 * 1
    output = O1
    endofrelease = N2

[contour]
    trigger = I2
    predelay = 0
    attack = _POT_1_1 * 40
    release = _POT_1_2 * 2
    level = L1.7 * -0.3 + 1
    output = O2
    endofrelease = N3

[contour]
    trigger = I3
    predelay = 0
    attack = _POT_1_1 * 60
    release = _POT_1_2 * 3
    level = L1.7 * -0.6 + 1
    output = O3
    endofrelease = N4

[copy]
    input = I4
    output = _EOA_1

# -------------------------------- envelopes group 2

[contour]
    trigger = I5 + _EOA_2_RETRIGGER
    loop = L1.4
    attack = _POT_2_1 * 20
    hold = _POT_2_2 * 1
    release = _POT_2_1 * 1
    output = O5
    endofrelease = N6

[contour]
    trigger = I6
    predelay = 0
    attack = _POT_2_1 * 40
    hold = _POT_2_2 * 2
    release = _POT_2_1 * 2
    level = L1.8 * -0.3 + 1
    output = O6
    endofrelease = N7

[contour]
    trigger = I7
    predelay = 0
    attack = _POT_2_1 * 60
    hold = _POT_2_2 * 3
    release = _POT_2_1 * 3
    level = L1.8 * -0.6 + 1
    output = O7
    endofrelease = N8

[copy]
    input = I8
    output = _EOA_2

# ------------------------------ buttons select group and pots

[buttongroup]
    button1 = B1.1
    button2 = B1.2
    led1 = L1.1
    led2 = L1.2

[pot]
    pot = P1.1
    select = L1.1
    output = _POT_1_1

[pot]
    pot = P1.2
    select = L1.1
    output = _POT_1_2

[pot]
    pot = P1.1
    select = L1.2
    output = _POT_2_1

[pot]
    pot = P1.2
    select = L1.2
    output = _POT_2_2

# ------------------------------ buttons for looping and output level decay

[button]
    button = B1.3
    onvalue = 1
    offvalue = 0
    led = L1.3

[button]
    button = B1.4
    onvalue = 1
    offvalue = 0
    led = L1.4

[button]
    button = B1.7
    onvalue = 1
    offvalue = 0
    led = L1.7

[button]
    button = B1.8
    onvalue = 1
    offvalue = 0
    led = L1.8

# ------------------------------ buttons third envelop re-triggers

[button]
    button = B1.5
    onvalue = 1
    offvalue = 0
    led = L1.5

[copy]
    input = L1.5 * _EOA_1
    output = _EOA_1_RETRIGGER

[button]
    button = B1.6
    onvalue = 1
    offvalue = 0
    led = L1.6

[copy]
    input = L1.6 * _EOA_2
    output = _EOA_2_RETRIGGER

# ------------------------------ output mixers

[mixer]
    input1 = O1
    input2 = O2
    input3 = O3
    output = O4

[mixer]
    input1 = O5
    input2 = O6
    input3 = O7
    output = O8
