# Techno Live patch v1.1

[p2b8]
[p2b8]
[p10]
[p10]

# --------------------- Clock

[buttongroup]
	button1 	= B1.7
	button2 	= B1.8
	button3 	= B2.7
	button4 	= B2.8
	led1 		= L1.7 
	led2 		= L1.8
	led3 		= L2.7
	led4 		= L2.8
	value1 	= P4.10 * 2.25	# 1.5 = 90  BPM
	value2 	= 2.08		# 125 BPM
	value3 	= 2.25		# 135 BPM
	value4 	= 2.33		# 140 BPM
	output 	= _CLOCK_HZ

[lfo]
    	hz 		= _CLOCK_HZ * 4
    	square 	= _CLOCK

[copy]
    	input 	= _CLOCK
    	output 	= G8

[copy]
    	input 	= _CLOCK
    	output 	= N8

[lfo]
    	hz 		= _CLOCK_HZ * 0.5
    	square 	= G6

[lfo]
    	hz 		= _CLOCK_HZ * 0.25
    	square 	= G4

[lfo]
    	hz 		= _CLOCK_HZ * 0.125
    	square 	= G2

# --------------------- Kick 

[buttongroup]
	button1 	= B1.2
	button2 	= B2.1
	button3 	= B2.2
	led1 		= L1.2 
	led2 		= L2.1
	led3 		= L2.2
	value1 	= 2		
	value2 	= 4	
	value3 	= 5	
	output 	= _KICK_PATTERN

[euklid]
	clock 	= _CLOCK
	length 	= 16
	Beats 	= _KICK_PATTERN
	offset 	= 0
	output	= _KICK

[button]
	button 	= B1.1
	led 		= L1.1

[copy]
    	input 	= _KICK * L1.1
    	output 	= G1

# --------------------- Sidechain envelope

[contour]
	trigger	= _KICK
	attack 	= 0
	release 	= P1.1 * 0.5
	negated 	= O8

# --------------------- Hats 

[buttongroup]
	button1 	= B1.4
	button2 	= B2.3
	button3 	= B2.4
	led1 		= L1.4 
	led2 		= L2.3
	led3 		= L2.4
	value1 	= 0	
	value2 	= 0.05	
	value3 	= 0.1	
	output 	= _HAT_DECAY_VARIATION

[euklid]
	clock 	= _CLOCK
	length 	= 16
	Beats 	= P2.1 * 12 + 4
	offset 	= 2
	output	= _HAT

[button]
	button 	= B1.3
	led 		= L1.3

[copy]
    	input 	= _HAT * L1.3
    	output 	= G3

[lfo]
    	hz 		= 3.5
	bipolar 	= off
    	sine 		= _HAT_LFO
	level		= _HAT_DECAY_VARIATION

[copy]
    	input 	= _HAT_LFO + 0.01
    	output 	= _HAT_LFO_1

[contour]
	trigger	= G3
	attack 	= 0
	release 	= P2.2 + _HAT_LFO_1
	output 	= O4

# --------------------- Percussion

[buttongroup]
	button1 	= B1.6
	button2 	= B2.5
	button3 	= B2.6
	led1 		= L1.6 
	led2 		= L2.5
	led3 		= L2.6
	value1 	= 13	
	value2 	= 14	
	value3 	= 15	
	output 	= _PERC_OFFSET

[euklid]
	clock 	= _CLOCK
	length 	= 16
	Beats 	= P1.2 * 15 + 1
	offset 	= _PERC_OFFSET
	output	= _PERC

[button]
	button 	= B1.5
	led 		= L1.5

[copy]
    	input 	= _PERC * L1.5
    	output 	= G5

# --------------------- Voice 1
# optional: normal to clock or use input :)

[contour]
	trigger	= _CLOCK	
	attack 	= P3.1
	release 	= P3.2 * 0.3 + 0.01
	output 	= O1

[lfo]
    	hz 		= P3.3 * 1
	bipolar 	= on
    	output	= O2
	waveform 	= P3.4 * 4
	level 	= 5V 

[copy]
    	input 	= G4
    	output 	= N3

[contour]
	trigger	= I3
	attack 	= P3.5 * 10
	release 	= P3.6 * 0.5
	output 	= O3

# --------------------- Voice 2

[contour]
	trigger	= _CLOCK
	attack 	= P4.1
	release 	= P4.2 * 0.3 + 0.01
	output 	= O5

[lfo]
    	hz 		= P4.3 * 10
	bipolar 	= on
    	sine		= O6
	level 	= P4.4 

