[droid]
    ledbrightness = 0.5

[p2b8]

# create distinct cv values for each step to identify the step position in the [compare] circuits
[sequencer] # 1. 16 steps (1-8)
	clock = I1
	reset = I2
	cvoutput = _step
	cv1 = 0.1
	cv2 = 0.2
	cv3 = 0.3
	cv4 = 0.4
	cv5 = 0.5
	cv6 = 0.6
	cv7 = 0.7
	cv8 = 0.8

# convert trigger inputs to gates
[contour]
	trigger = I8 # trigger input sent from Kompas (pulses of 5.5 V)
	attack = 0
	hold = 0.18 # buggy manual says 0.5 means a hold time of 5 seconds -> here: 0.18 = 0.09 s
	release = 0
	output = _NR_prime

# check output
#[copy]
#	input = _NR_prime  # low = 0.4 V ; gate of 0.09 s and 10.74 V
#	output = O8

# send a trigger/gate every step 1
[compare]
	input = _step
	compare = 0.1
	precision = 0.01
	ifequal = 1 # else = 0 (default)
	output = _trigger_sh1

# check output
#[copy]
##	input = _trigger_sh1   # low = 0.4 V ; gate of 0.12 s at 10.74 V
#	input = _trigger_sh7   # low = 0.4 V ; gate of 0.12 s at 10.74 V
#	output = O7

# sample state on/off of step 1 of the input sequence
[sample]
	input = _NR_prime
	sample = _trigger_sh1
	timewindow = 0.01 # unit is seconds
	output = _button1

# send state only if different from current state, as algoquencer buttons are toggle buttons
[logic]
	input1 = _button1
	input2 = L1.1
	nand = _button1_toggle
#	nand = O7

# check output
#[copy]
##	input = _button1       # gate low/high with 0.4/10.74 V
#	input = _button1_toggle       # gate low/high with 0.4/10.74 V
#	output = O7

# same for steps 2-8 ...
[compare]
	input = _step
	compare = 0.2
	precision = 0.01
	ifequal = 1
	output = _trigger_sh2
	
[sample]
	input = _NR_prime
	sample = _trigger_sh2
	timewindow = 0.01
	output = _button2

[logic]
	input1 = _button2
	input2 = L1.2
	nand = _button2_toggle

[compare]
	input = _step
	compare = 0.3
	precision = 0.01
	ifequal = 1
	output = _trigger_sh3
	
[sample]
	input = _NR_prime
	sample = _trigger_sh3
	timewindow = 0.01
	output = _button3

[logic]
	input1 = _button3
	input2 = L1.3
	nand = _button3_toggle

[compare]
	input = _step
	compare = 0.4
	precision = 0.01
	ifequal = 1
	output = _trigger_sh4
	
[sample]
	input = _NR_prime
	sample = _trigger_sh4
	timewindow = 0.01
	output = _button4

[logic]
	input1 = _button4
	input2 = L1.4
	nand = _button4_toggle

[compare]
	input = _step
	compare = 0.4
	precision = 0.01
	ifequal = 1
	output = _trigger_sh5
	
[sample]
	input = _NR_prime
	sample = _trigger_sh5
	timewindow = 0.01
	output = _button5

[logic]
	input1 = _button5
	input2 = L1.5
	nand = _button5_toggle

[compare]
	input = _step
	compare = 0.6
	precision = 0.01
	ifequal = 1
	output = _trigger_sh6
	
[sample]
	input = _NR_prime
	sample = _trigger_sh6
	timewindow = 0.01
	output = _button6

[logic]
	input1 = _button6
	input2 = L1.6
	nand = _button6_toggle

[compare]
	input = _step
	compare = 0.7
	precision = 0.01
	ifequal = 1
	output = _trigger_sh7
	
[sample]
	input = _NR_prime
	sample = _trigger_sh7
	timewindow = 0.01
	output = _button7

[logic]
	input1 = _button7
	input2 = L1.7
	nand = _button7_toggle

[compare]
	input = _step
	compare = 0.8
	precision = 0.01
	ifequal = 1
	output = _trigger_sh8
	
[sample]
	input = _NR_prime
	sample = _trigger_sh8
	timewindow = 0.01
	output = _button8

[logic]
	input1 = _button8
	input2 = L1.8
	nand = _button8_toggle

# note: buttons of algoquencer are toggle buttons!
[algoquencer]
	clock = I1
	reset = I2
	trigger = O8 # output intended to trigger a drum voice
	activity = P1.1
 	button1 = _button1_toggle
	button2 = _button2_toggle
	button3 = _button3_toggle
	button4 = _button4_toggle
	button5 = _button5_toggle
	button6 = _button6_toggle
	button7 = _button7_toggle
	button8 = _button8_toggle
# check result visually
	led1 = L1.1
	led2 = L1.2
	led3 = L1.3
	led4 = L1.4
	led5 = L1.5
	led6 = L1.6
	led7 = L1.7
	led8 = L1.8
