[p2b8]
[p2b8]
[p10]
[p10]

# -------------------------------------------------
# General
# -------------------------------------------------

# Master clock
[lfo]
    hz = P1.1 * 6 + 4
    level = 1
    square = N1

# Copy clock or clock input G1
[copy]
    input = I1
    output = G1

# Clock div 3
[clocktool]
    clock = I1
    reset = I2
    divide = 3
    output = G3

# Clock div 4
[clocktool]
    clock = I1
    reset = I2
    divide = 4
    output = G5

# Clock div 5
[clocktool]
    clock = I1
    reset = I2
    divide = 5
    output = G7

[lfo]
    hz = P4.3 * 10
    level = P4.5
    bipolar = 1
    sine = O7

[lfo]
    hz = P4.4 * 10
    level = P4.6
    bipolar = 1
    sine = O8

[contour]
    trigger = G6
    attack = P3.1 * 0.3 + 0.01
    release = P3.2
    output = O3

[contour]
    trigger = G8
    attack = P4.1 * 0.3 + 0.01
    release = P4.2
    output = O4

# -------------------------------------------------
# Kick
# -------------------------------------------------

[compare]
    input = P1.2
    compare = 0
    precision = 0.15
    ifequal = 1
    else = 0
    output = _SELECT_1

[algoquencer]
    select = _SELECT_1
    clock = I1
    reset = I2 + _RESET_ALL
    button1 = B1.1
    button2 = B1.2
    button3 = B2.1
    button4 = B2.2
    button5 = B1.3
    button6 = B1.4
    button7 = B2.3
    button8 = B2.4
    button9 = B1.5
    button10 = B1.6
    button11 = B2.5
    button12 = B2.6
    button13 = B1.7
    button14 = B1.8
    button15 = B2.7
    button16 = B2.8
    activity = P2.1
    led1 = L1.1
    led2 = L1.2
    led3 = L2.1
    led4 = L2.2
    led5 = L1.3
    led6 = L1.4
    led7 = L2.3
    led8 = L2.4
    led9 = L1.5
    led10 = L1.6
    led11 = L2.5
    led12 = L2.6
    led13 = L1.7
    led14 = L1.8
    led15 = L2.7
    led16 = L2.8
    trigger = _TRIG_KICK

# -------------------------------------------------
# Drums
# -------------------------------------------------

[compare]
    input = P1.2
    compare = 0.25
    precision = 0.15
    ifequal = 1
    else = 0
    output = _SELECT_2

[algoquencer]
    select = _SELECT_2
    clock = I1
    reset = I2 + _RESET_ALL
    reroll = _REROLL_DRUMS
    button1 = B1.1
    button2 = B1.2
    button3 = B2.1
    button4 = B2.2
    button5 = B1.3
    button6 = B1.4
    button7 = B2.3
    button8 = B2.4
    button9 = B1.5
    button10 = B1.6
    button11 = B2.5
    button12 = B2.6
    button13 = B1.7
    button14 = B1.8
    button15 = B2.7
    button16 = B2.8
    activity = P2.1
    led1 = L1.1
    led2 = L1.2
    led3 = L2.1
    led4 = L2.2
    led5 = L1.3
    led6 = L1.4
    led7 = L2.3
    led8 = L2.4
    led9 = L1.5
    led10 = L1.6
    led11 = L2.5
    led12 = L2.6
    led13 = L1.7
    led14 = L1.8
    led15 = L2.7
    led16 = L2.8
    trigger = _TRIG_DRUMS
    pitch = _PITCH_DRUMS

[lfo]
    hz = 1
    level = 1 * _DRUMS_ADD_SINE + _DRUMS_ADD_MORE_SINE
    bipolar = 0
    sine = _DRUM_LFO

[mixer]
    input1 = _PITCH_DRUMS
    input2 = _DRUM_LFO
    output = O2

# -------------------------------------------------
# Bass
# -------------------------------------------------

[compare]
    input = P1.2
    compare = 0.5
    precision = 0.15
    ifequal = 1
    else = 0
    output = _SELECT_3

[algoquencer]
    select = _SELECT_3
    clock = I1
    reset = I3 + _RESET_ALL
    button1 = B1.1
    button2 = B1.2
    button3 = B2.1
    button4 = B2.2
    button5 = B1.3
    button6 = B1.4
    button7 = B2.3
    button8 = B2.4
    button9 = B1.5
    button10 = B1.6
    button11 = B2.5
    button12 = B2.6
    button13 = B1.7
    button14 = B1.8
    button15 = B2.7
    button16 = B2.8
    activity = P2.2
    variation = P3.3
    morphs = P3.3
    pitch1 = P3.7 * 0.3
    pitch2 = P3.8 * 0.3
    pitch3 = P4.7 * 0.3
    pitch4 = P4.8 * 0.3
    pitch5 = P3.9 * 0.3
    pitch6 = P3.10 * 0.3
    pitch7 = P4.9 * 0.3
    pitch8 = P4.10 * 0.3
    pitch9 = P3.7 * 0.3
    pitch10 = P3.8 * 0.3
    pitch11 = P4.7 * 0.3
    pitch12 = P4.8 * 0.3
    pitch13 = P3.9 * 0.3
    pitch14 = P3.10 * 0.3
    pitch15 = P4.9 * 0.3
    pitch16 = P4.10 * 0.3
    led1 = L1.1
    led2 = L1.2
    led3 = L2.1
    led4 = L2.2
    led5 = L1.3
    led6 = L1.4
    led7 = L2.3
    led8 = L2.4
    led9 = L1.5
    led10 = L1.6
    led11 = L2.5
    led12 = L2.6
    led13 = L1.7
    led14 = L1.8
    led15 = L2.7
    led16 = L2.8
    trigger = _TRIG_BASS
    pitch = _PITCH_BASS

[minifonion]
    input = _PITCH_BASS
    trigger = _TRIG_BASS
    root = 0
    degree = 7
    output = O1

# -------------------------------------------------
# Lead
# -------------------------------------------------

[compare]
    input = P1.2
    compare = 0.75
    precision = 0.15
    ifequal = 1
    else = 0
    output = _SELECT_4

[algoquencer]
    select = _SELECT_4
    clock = I1
    reset = I4 + _RESET_ALL
    reroll = _REROLL_LEAD
    button1 = B1.1
    button2 = B1.2
    button3 = B2.1
    button4 = B2.2
    button5 = B1.3
    button6 = B1.4
    button7 = B2.3
    button8 = B2.4
    button9 = B1.5
    button10 = B1.6
    button11 = B2.5
    button12 = B2.6
    button13 = B1.7
    button14 = B1.8
    button15 = B2.7
    button16 = B2.8
    activity = P2.2
    variation = P3.5
    morphs = P3.6
    led1 = L1.1
    led2 = L1.2
    led3 = L2.1
    led4 = L2.2
    led5 = L1.3
    led6 = L1.4
    led7 = L2.3
    led8 = L2.4
    led9 = L1.5
    led10 = L1.6
    led11 = L2.5
    led12 = L2.6
    led13 = L1.7
    led14 = L1.8
    led15 = L2.7
    led16 = L2.8
    trigger = _TRIG_LEAD
    pitch = _PITCH_LEAD

[minifonion]
    input = _PITCH_LEAD
    trigger = _TRIG_LEAD
    root = 0
    degree = 7
    output = O5

# -------------------------------------------------
# Master page
# -------------------------------------------------

[compare]
    input = P1.2
    compare = 1
    precision = 0.15
    ifequal = 1
    else = 0
    output = _SELECT_5

# Mute 1
[button]
    button = B1.1
    select = _SELECT_5
    onvalue = _TRIG_KICK
    offvalue = 0
    led = L1.1
    output = G2

[button]
    states = 1
    button = B1.2
    select = _SELECT_5
    led = L1.2

[button]
    states = 1
    button = B2.1
    select = _SELECT_5
    led = L2.1

# Reset all patterns
[button]
    states = 1
    button = B2.2
    select = _SELECT_5
    led = L2.2
    output = _RESET_ALL

# Mute 2
[button]
    button = B1.3
    select = _SELECT_5
    onvalue = _TRIG_DRUMS
    offvalue = 0
    led = L1.3
    output = G4

# Drums re-roll
[button]
    states = 1
    button = B1.4
    select = _SELECT_5
    led = L1.4
    output = _REROLL_DRUMS

# Drums add light variation
[button]
    button = B2.3
    select = _SELECT_5
    onvalue = 0.05
    offvalue = 0
    led = L2.3
    output = _DRUMS_ADD_SINE

# Drums add random
[button]
    button = B2.4
    select = _SELECT_5
    onvalue = 0.5
    offvalue = 0
    led = L2.4
    output = _DRUMS_ADD_MORE_SINE

# Mute 3
[button]
    button = B1.5
    select = _SELECT_5
    onvalue = _TRIG_BASS
    offvalue = 0
    led = L1.5
    output = G6

[button]
    states = 1
    button = B1.6
    select = _SELECT_5
    led = L1.6

[button]
    states = 1
    button = B2.5
    select = _SELECT_5
    led = L2.5

[button]
    states = 1
    button = B2.6
    select = _SELECT_5
    led = L2.6

# Mute 4
[button]
    button = B1.7
    select = _SELECT_5
    onvalue = _TRIG_LEAD
    offvalue = 0
    led = L1.7
    output = G8

# Lead re-roll
[button]
    states = 1
    button = B1.8
    select = _SELECT_5
    led = L1.8
    output = _REROLL_LEAD

[button]
    states = 1
    button = B2.7
    select = _SELECT_5
    led = L2.7

[button]
    states = 1
    button = B2.8
    select = _SELECT_5
    led = L2.8
