# Monotrail Four 8 step pattern sequencers with mute function

# P1.1 selects one of five pages
# 1st four pages are 8 step patterns for O1>O4
# page 5 left vertical row are mutes for the 4 patterns
# page 5 right vertical row turns activity on for that pattern 
# p1.2 sets activity - from 0.5 to 1.5
# I1 is a clock


[p2b8]

[algoquencer]
    select = _SELECT_1
    clock = I1
    reset = I2
    button1 = B1.1
    button2 = B1.2
    button3 = B1.3
    button4 = B1.4
    button5 = B1.5
    button6 = B1.6
    button7 = B1.7
    button8 = B1.8
    activity = P1.2 * _ACT_1 + 0.5
    led1 = L1.1
    led2 = L1.2
    led3 = L1.3
    led4 = L1.4
    led5 = L1.5
    led6 = L1.6
    led7 = L1.7
    led8 = L1.8
    trigger = _TRIG_1

[compare]
    input = P1.1
    compare = 0
    precision = 0.15
    ifequal = 1
    else = 0
    output = _SELECT_1

[algoquencer]
    select = _SELECT_2
    clock = I1
    reset = I2
    button1 = B1.1
    button2 = B1.2
    button3 = B1.3
    button4 = B1.4
    button5 = B1.5
    button6 = B1.6
    button7 = B1.7
    button8 = B1.8
    activity = P1.2 * _ACT_2 + 0.5
    led1 = L1.1
    led2 = L1.2
    led3 = L1.3
    led4 = L1.4
    led5 = L1.5
    led6 = L1.6
    led7 = L1.7
    led8 = L1.8
    trigger = _TRIG_2

[compare]
    input = P1.1
    compare = 0.25
    precision = 0.15
    ifequal = 1
    else = 0
    output = _SELECT_2

[algoquencer]
    select = _SELECT_3
    clock = I1
    reset = I2
    button1 = B1.1
    button2 = B1.2
    button3 = B1.3
    button4 = B1.4
    button5 = B1.5
    button6 = B1.6
    button7 = B1.7
    button8 = B1.8
    activity = P1.2 * _ACT_3 + 0.5
    led1 = L1.1
    led2 = L1.2
    led3 = L1.3
    led4 = L1.4
    led5 = L1.5
    led6 = L1.6
    led7 = L1.7
    led8 = L1.8
    trigger = _TRIG_3

[compare]
    input = P1.1
    compare = 0.5
    precision = 0.15
    ifequal = 1
    else = 0
    output = _SELECT_3

[algoquencer]
    select = _SELECT_4
    clock = I1
    reset = I2
    button1 = B1.1
    button2 = B1.2
    button3 = B1.3
    button4 = B1.4
    button5 = B1.5
    button6 = B1.6
    button7 = B1.7
    button8 = B1.8
    activity = P1.2 * _ACT_4 + 0.5
    led1 = L1.1
    led2 = L1.2
    led3 = L1.3
    led4 = L1.4
    led5 = L1.5
    led6 = L1.6
    led7 = L1.7
    led8 = L1.8
    trigger = _TRIG_4

[compare]
    input = P1.1
    compare = 0.75
    precision = 0.15
    ifequal = 1
    else = 0
    output = _SELECT_4

[compare]
    input = P1.1
    compare = 1
    precision = 0.15
    ifequal = 1
    else = 0
    output = _SELECT_5

[button]
    button = B1.1
    select = _SELECT_5
    onvalue = _TRIG_1
    offvalue = 0
    led = L1.1
    output = O1

[button]
    button = B1.3
    select = _SELECT_5
    onvalue = _TRIG_2
    offvalue = 0
    led = L1.3
    output = O2

[button]
    button = B1.5
    select = _SELECT_5
    onvalue = _TRIG_3
    offvalue = 0
    led = L1.5
    output = O3

[button]
    button = B1.7
    select = _SELECT_5
    onvalue = _TRIG_4
    offvalue = 0
    led = L1.7
    output = O4

[button]
    button = B1.2
    select = _SELECT_5
    led = L1.2
    output = _ACT_1

[button]
    button = B1.4
    select = _SELECT_5
    led = L1.4
    output = _ACT_2

[button]
    button = B1.6
    select = _SELECT_5
    led = L1.6
    output = _ACT_3

[button]
    button = B1.8
    select = _SELECT_5
    led = L1.8
    output = _ACT_4

[lfo]
    hz = 2.08 * 4
    level = 1
    square = N1
