# Monotrail OCTA-LFO v2.5

# 2 horizontal groups of 4 LFOs
# Each first LFO is related to the master clock - P1.1 
# Each next LFO is half the speed of the previous in the group
# Group 2 has a slightly wider range, creating subte shifts to group 1
# Group 1 can be synced to ext. clock with I1 - Group 2 stays free running
# left column of knobs P1.1/3/5/7 control shape for LFOs in group 1
# Right column of knobs P1.2/4/6/8 control shape for LFOs in group 2
# LFOs O2>O4 (group 1) can be VC with I2>I4 
# LFOs O5>O8 (group 2) can be VC with I5>I8
# P1.2 is used as a global attenuator for inputs 2 > 8


[p2b8]

# --------------------- Clock and normalization

[lfo]
    	hz 		= P1.1 * 10 + 1
    	square 	= _CLOCK

[copy]
    	input 	= _CLOCK
    	output 	= N1

# --------------------- LFOs group 1

[lfo]
   	taptempo 	= I1			
    	bipolar 	= on
    	sine 		= _SINE_1
   	sawtooth 	= _SAWTOOTH_1
    	ramp 		= _RAMP_1
    	square 	= _SQUARE_1
    	level 	= 5V  	

[button]
    	button 	= B1.1
    	led 		= L1.1
    	value1 	= _SINE_1
    	value2 	= _SAWTOOTH_1
    	value3 	= _RAMP_1
    	value4 	= _SQUARE_1
    	output 	= O1

[lfo]
    	taptempo 	= I1 
    	rate 		= I2 * P1.2 - 1V
    	bipolar 	= on
    	sine 		= _SINE_2
   	sawtooth 	= _SAWTOOTH_2
    	ramp 		= _RAMP_2
    	square 	= _SQUARE_2
    	level 	= 5V  	

[button]
    	button 	= B1.3
    	led 		= L1.3
    	value1 	= _SINE_2
    	value2 	= _SAWTOOTH_2
    	value3 	= _RAMP_2
    	value4 	= _SQUARE_2
    	output 	= O2

[lfo]
    	taptempo 	= I1
    	rate 		= I3 * P1.2 - 2V
    	bipolar 	= on
    	sine 		= _SINE_3
   	sawtooth 	= _SAWTOOTH_3
    	ramp 		= _RAMP_3
    	square 	= _SQUARE_3
    	level 	= 5V  	

[button]
    	button 	= B1.5
    	led 		= L1.5
    	value1 	= _SINE_3
    	value2 	= _SAWTOOTH_3
    	value3 	= _RAMP_3
    	value4 	= _SQUARE_3
    	output 	= O3

[lfo]
    	taptempo 	= I1
    	rate 		= I4 * P1.2 - 3V
    	bipolar 	= on
    	sine 		= _SINE_4
   	sawtooth 	= _SAWTOOTH_4
    	ramp 		= _RAMP_4
    	square 	= _SQUARE_4
    	level 	= 5V  	

[button]
    	button 	= B1.7
    	led 		= L1.7
    	value1 	= _SINE_4
    	value2 	= _SAWTOOTH_4
    	value3 	= _RAMP_4
    	value4 	= _SQUARE_4
    	output 	= O4

# --------------------- LFO group 02

[lfo]
    	hz 		= P1.1 * 12
	rate		= I5 * P1.2
    	bipolar 	= on
    	sine 		= _SINE_5
   	sawtooth 	= _SAWTOOTH_5
    	ramp 		= _RAMP_5
    	square 	= _SQUARE_5
    	level 	= 5V  	

[button]
    	button 	= B1.2
    	led 		= L1.2
    	value1 	= _SINE_5
    	value2 	= _SAWTOOTH_5
    	value3 	= _RAMP_5
    	value4 	= _SQUARE_5
    	output 	= O5

[lfo]
    	hz 		= P1.1 * 6
	rate		= I6 * P1.2
    	bipolar 	= on
    	sine 		= _SINE_6
   	sawtooth 	= _SAWTOOTH_6
    	ramp 		= _RAMP_6
    	square 	= _SQUARE_6
    	level 	= 5V  	

[button]
    	button 	= B1.4
    	led 		= L1.4
    	value1 	= _SINE_6
    	value2 	= _SAWTOOTH_6
    	value3 	= _RAMP_6
    	value4 	= _SQUARE_6
    	output 	= O6

[lfo]
    	hz 		= P1.1 * 3
	rate		= I7 * P1.2
   	bipolar 	= on
    	sine 		= _SINE_7
   	sawtooth 	= _SAWTOOTH_7
    	ramp 		= _RAMP_7
    	square 	= _SQUARE_7
    	level 	= 5V  	

[button]
    	button 	= B1.6
    	led 		= L1.6
    	value1 	= _SINE_7
    	value2 	= _SAWTOOTH_7
    	value3 	= _RAMP_7
    	value4 	= _SQUARE_7
    	output 	= O7

[lfo]
   	hz 		= P1.1 * 1.5
	rate		= I8 * P1.2
    	bipolar 	= on
    	sine 		= _SINE_8
   	sawtooth 	= _SAWTOOTH_8
    	ramp 		= _RAMP_8
    	square 	= _SQUARE_8
    	level 	= 5V  	

[button]
    	button 	= B1.8
    	led 		= L1.8
    	value1 	= _SINE_8
    	value2 	= _SAWTOOTH_8
    	value3 	= _RAMP_8
    	value4 	= _SQUARE_8
    	output 	= O8
	