#!/usr/bin/env python3
"""
DROID CV Tool Patch Builder

Assembles a DROID .ini patch from a YAML config that picks and connects
CV tool modules from the library.

Usage:
    python cv-tools/builder.py <config.yaml> [-o output.ini]
"""

import argparse
import importlib
import importlib.util
import sys
import textwrap
from datetime import date
from pathlib import Path

# Add tools directory to path
TOOLS_DIR = Path(__file__).parent / "tools"
sys.path.insert(0, str(TOOLS_DIR.parent))

# Try YAML, fall back to simple parser
try:
    import yaml
except ImportError:
    yaml = None


def parse_yaml_simple(path):
    """Minimal YAML-subset parser for when PyYAML isn't installed.
    Handles the flat key: value and nested list-of-dict structure we need."""
    import json
    text = Path(path).read_text(encoding="utf-8")
    # Strip comments
    lines = []
    for line in text.split("\n"):
        stripped = line.split(" #")[0].rstrip()
        if stripped.startswith("#"):
            continue
        lines.append(stripped)
    # Try JSON-style parse of cleaned YAML (works for simple cases)
    # For real projects, install PyYAML
    raise ImportError(
        "PyYAML not installed. Install with: pip install pyyaml\n"
        "Or use a JSON config file instead."
    )


def load_config(path):
    """Load a patch config from YAML or JSON."""
    path = Path(path)
    text = path.read_text(encoding="utf-8")

    if path.suffix == ".json":
        import json
        return json.loads(text)

    if yaml:
        return yaml.safe_load(text)

    return parse_yaml_simple(path)


def load_tool_module(tool_name):
    """Dynamically import a tool module from cv-tools/tools/."""
    mod_path = TOOLS_DIR / f"{tool_name}.py"
    if not mod_path.exists():
        raise FileNotFoundError(f"Tool module not found: {mod_path}")

    spec = importlib.util.spec_from_file_location(f"tools.{tool_name}", mod_path)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


# ─── Tool base class and registry ────────────────────────────────

class ToolInstance:
    """A configured instance of a CV tool in a patch."""

    def __init__(self, tool_name, instance_name, config, tool_module):
        self.tool_name = tool_name
        self.instance_name = instance_name
        self.config = config
        self.module = tool_module
        self.meta = tool_module.TOOL_META

        # Resolve port assignments from config
        self.inputs = config.get("inputs", {})
        self.outputs = config.get("outputs", {})
        self.controls = config.get("controls", {})

    def validate(self):
        """Check that all required ports are assigned."""
        errors = []
        for port in self.meta.get("required_inputs", []):
            if port not in self.inputs:
                errors.append(f"{self.instance_name}: missing required input '{port}'")
        for port in self.meta.get("required_outputs", []):
            if port not in self.outputs:
                errors.append(f"{self.instance_name}: missing required output '{port}'")
        for port in self.meta.get("required_controls", []):
            if port not in self.controls:
                errors.append(f"{self.instance_name}: missing required control '{port}'")
        return errors

    def render(self):
        """Render this tool's DROID .ini circuits."""
        return self.module.render(
            name=self.instance_name,
            inputs=self.inputs,
            outputs=self.outputs,
            controls=self.controls,
        )


# ─── Patch builder ────────────────────────────────────────────────

class PatchBuilder:
    """Assembles a complete DROID patch from tool instances."""

    def __init__(self, config):
        self.config = config
        self.name = config.get("name", "CV Tool Patch")
        self.description = config.get("description", "")
        self.controllers = config.get("controllers", [])
        self.tool_instances = []

    def load_tools(self):
        """Load and instantiate all tools from config."""
        for tool_cfg in self.config.get("tools", []):
            tool_name = tool_cfg["tool"]
            instance_name = tool_cfg.get("name", tool_name)
            module = load_tool_module(tool_name)
            instance = ToolInstance(tool_name, instance_name, tool_cfg, module)
            self.tool_instances.append(instance)

    def validate(self):
        """Validate all tool instances."""
        all_errors = []
        for inst in self.tool_instances:
            all_errors.extend(inst.validate())
        return all_errors

    def render_header(self):
        """Render the patch header with I/O documentation."""
        lines = [
            f"# {self.name}",
            f"# {self.description}",
            f"# Generated by DROID CV Tool Builder — {date.today().isoformat()}",
            "#",
        ]

        # Collect all physical I/O assignments for documentation
        inputs_used = {}
        outputs_used = {}
        controls_used = {}

        for inst in self.tool_instances:
            for port, hw in inst.inputs.items():
                if hw.startswith("I") and not hw.startswith("_"):
                    inputs_used[hw] = f"{inst.instance_name}.{port}"
            for port, hw in inst.outputs.items():
                if hw.startswith("O") or hw.startswith("G"):
                    if not hw.startswith("_"):
                        outputs_used[hw] = f"{inst.instance_name}.{port}"
            for port, hw in inst.controls.items():
                controls_used[hw] = f"{inst.instance_name}.{port}"

        if inputs_used:
            lines.append("# INPUTS:")
            for hw in sorted(inputs_used):
                lines.append(f"#  {hw}: [{inputs_used[hw]}]")
            lines.append("#")

        if outputs_used:
            lines.append("# OUTPUTS:")
            for hw in sorted(outputs_used):
                lines.append(f"#  {hw}: [{outputs_used[hw]}]")
            lines.append("#")

        if controls_used:
            # Group by controller
            by_controller = {}
            for hw, desc in sorted(controls_used.items()):
                # Extract controller number from e.g. P1.2, B2.3
                parts = hw.split(".")
                if len(parts) == 2:
                    ctrl_type = parts[0][0]  # P, B, L, S, E, F
                    ctrl_num = parts[0][1:]
                    key = f"Controller {ctrl_num}"
                    if key not in by_controller:
                        by_controller[key] = []
                    by_controller[key].append((hw, desc))

            for ctrl, mappings in sorted(by_controller.items()):
                ctrl_idx = int(ctrl.split()[-1]) - 1
                ctrl_type = self.controllers[ctrl_idx] if ctrl_idx < len(self.controllers) else "unknown"
                lines.append(f"# {ctrl.upper()} ({ctrl_type}):")
                for hw, desc in sorted(mappings):
                    lines.append(f"#  {hw}: [{desc}]")
                lines.append("#")

        return "\n".join(lines)

    def render_controllers(self):
        """Render controller declarations."""
        lines = []
        for i, ctrl in enumerate(self.controllers):
            lines.append(f"[{ctrl}]")
        return "\n".join(lines)

    def render(self):
        """Render the complete patch."""
        sections = [
            self.render_header(),
            "",
            self.render_controllers(),
        ]

        for inst in self.tool_instances:
            sections.append("")
            sections.append(f"# {'=' * 57}")
            sections.append(f"# {inst.instance_name.upper()} — {inst.meta['description']}")
            sections.append(f"# (Doepfer {inst.meta.get('doepfer', 'N/A')})")
            sections.append(f"# {'=' * 57}")
            sections.append("")
            sections.append(inst.render())

        return "\n".join(sections) + "\n"


# ─── CLI ──────────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser(description="DROID CV Tool Patch Builder")
    parser.add_argument("config", nargs="?", help="Path to patch config (YAML or JSON)")
    parser.add_argument("-o", "--output", help="Output .ini file path")
    parser.add_argument("--validate-only", action="store_true",
                        help="Only validate, don't generate")
    parser.add_argument("--list-tools", action="store_true",
                        help="List available tools and exit")
    args = parser.parse_args()

    if args.list_tools:
        print("Available CV tools:")
        print("-" * 60)
        for f in sorted(TOOLS_DIR.glob("*.py")):
            if f.name.startswith("_"):
                continue
            try:
                mod = load_tool_module(f.stem)
                meta = mod.TOOL_META
                print(f"  {f.stem:24s} {meta.get('doepfer', ''):8s} {meta['description']}")
            except Exception as e:
                print(f"  {f.stem:24s} (error: {e})")
        return

    if not args.config:
        parser.error("config is required (unless using --list-tools)")

    config = load_config(args.config)
    builder = PatchBuilder(config)
    builder.load_tools()

    errors = builder.validate()
    if errors:
        print("Validation errors:", file=sys.stderr)
        for e in errors:
            print(f"  - {e}", file=sys.stderr)
        if not args.validate_only:
            print("\nGeneration aborted.", file=sys.stderr)
            sys.exit(1)
        return

    if args.validate_only:
        print("Validation passed.")
        return

    patch = builder.render()

    if args.output:
        Path(args.output).write_text(patch, encoding="utf-8")
        print(f"Patch written to {args.output}")
    else:
        print(patch)


if __name__ == "__main__":
    main()
